### ISSUE TITLE
Upgrade TagField for SS4 to use react-select

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-tagfield#110]
We use [react-select](https://jedwatson.github.io/react-select/) in silverstripe/admin for fields like TreeDropdownField.

We should replace the chosen implementation with an example like this:

![image](https://user-images.githubusercontent.com/5170590/38587732-bb26abe8-3d76-11e8-9b99-eedf33a64cb1.png)

**Comment by andrewandante** [comment]
Yes please - currently want to have a tagfield in my AssetAdmin and I can't 😢 

Would have a crack if my React was up to it - tempted for Hackday if you have any pointers or anyone else does :)
