### ISSUE TITLE
Using TagField with SiteTree/Pages

### ISSUE THREAD

**Issue by chromos33** [silverstripe/silverstripe-tagfield#111]
Currently am trying to Use the Tagfield to reference Pages onto an Object so I can render them.
Problem is I get a Server Error
`HY000-3065: Expression #1 of ORDER BY clause is not in SELECT list, references column 'DATABASENAME.SiteTree.Title' which is not in SELECT list; this is incompatible with DISTINCT,`

currently am simply going to copy the Field into a new Class and disable sorting
 to "fix" this.

Using Silverstrip 4.0, Mysql 5.7.22
"silverstripe/tagfield": "^2.0",

**Comment by dhensby** [comment]
Where is the sort part coming from?

**Comment by chromos33** [comment]
TagField.php line 416 though I since gave up using the Tagfield as dnadesign/silverstripe-elemental
produced some problems after my work around with the Tagfield

**Comment by chromos33** [comment]
Can be Closed solved it by 
Adding an extra field to the object  and excluding that field from fluents query rewriting that seems to solve the problem.
