### ISSUE TITLE
Add a slight delay before performing lazy load searches

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-tagfield#123]
@robbieaverill commented on [Thu Nov 15 2018](https://github.com/silverstripe/silverstripe-blog/issues/561)

**Version: 2.2.x-dev** (React version)

When I type "test" into a lazy loadable TagField, I see four network requests:

![image](https://user-images.githubusercontent.com/5170590/48577896-fc8b1a00-e920-11e8-902e-ca4de2a90115.png)

We could put a half second resettable timeout in before we perform the XHR request to help prevent this.

### PR

#124

**Comment by robbieaverill** [comment]
I'm going to suggest we do this now - on a larger site, performing lots of these requests means it takes a while to suggest options in a lazy loaded tag field, which makes it difficult to use.

**Comment by ScopeyNZ** [comment]
PR @ #124
