### ISSUE TITLE
Changes should not be tracked until a tag is added

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-tagfield#125]
### Description

Currently when using tag field in the context of a CMS edit page the input is being marked as changed while searching for tags to select. Ideally a change would only be tracked when tags are added or removed (ie. different from the tags that were there originally)

### Steps to reproduce

- Add a tag field to CMS form for a page (or just edit a blog page for an example)
- Type in the tag field to search for tags
- Note that the save/publish buttons in the "south toolbar" show as green implying there are unsaved changes

**Comment by michalkleiner** [comment]
Released in 2.10.1
