### ISSUE TITLE
minor suggestion to update ReadMe with note from docs

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-tagfield#134]
Just a quick note to say I think this note should be in the main Read Me:
This assumes you have imported the namespaces class, e.g. use SilverStripe\TagField\TagField;

This really threw me: Until I eventually spotted this note in the Note in docs/en (hard to spot) I was trying SilverStripe\TagField;

**Comment by robbieaverill** [comment]
Yeah fair enough, sorry it wasted your time! Would you like to submit a pull request to add that to the readme?
