### ISSUE TITLE
issue with setIsMultiple(false) - field does not display value

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-tagfield#143]
If I create a `TagField` or `StringTagField` with `setIsMultiple(false)` then there appears to be an issue with the displaying of the value. You are able to save the new/old value (and it writes to the DB) but when the form re-renders the field has no value, when making changes to other fields on the page this results in the previously entered value to be cleared.

SilverStripe 4.3.2 and tagfield 2.2.3

**Comment by wilr** [comment]
Fixed in #201
