### ISSUE TITLE
How to use in Frontend Forms?

### ISSUE THREAD

**Issue by cloph** [silverstripe/silverstripe-tagfield#145]
It works fine in Backend, but there doesn't seem to be a way to use the TagField in Frontend forms (i.e. render it to a Page.ss template for a end-user form).

I might have missed something, but I couldn't find anything in the docs, and just trying to use it renders some meta-data to the page that would need to be parsed/interpreted.

So this issue is a about either
* updating the documentation/README.md that the module is solely for admin backend
* providing some hints on how to use it in a frontend form…

**Comment by chillu** [comment]
Added a note to this effect: https://github.com/silverstripe/silverstripe-tagfield/commit/ec8ca5bf2aff6c3f7b1a85062945d4037cc48e54
