### ISSUE TITLE
SS4 Tagfield  with AssetAdmin

### ISSUE THREAD

**Issue by klausjulius** [silverstripe/silverstripe-tagfield#147]

**Comment by klausjulius** [comment]
Hi together,

i installed the fixed version of tagfield (silverstripe-tagfield-58edb12fa36b63145a34ca793a79a27c852d2733).
now tagfield works with AssetAdmin. I can create tags and save them.
existing tags are shown on input.

the tags are saved in a $many_many relation. this works fine.
in the database the tags and there relation are saved correctly.
only when i reload the page or switch to new data, the tags are not displayed.

Saving works, loading not.

`$fields->insertAfter('Title', TagField::create('Keywords', 'Schlagworte', MosaikKeywords::get(), $MFile->Keywords(), 'Keyword')->setShouldLazyLoad(true)->setCanCreate(true));`

hope someone can help

bye 

Klaus

**Comment by robbieaverill** [comment]
Assuming this is a bug report, you can use the latest release branch 2.4.x-dev, it’s fixed there and will be released soon

**Comment by klausjulius** [comment]
Hi Robbie,

thanks for your answer. Do you know when it will be released.

Bye

Klaus

Von: Robbie Averill [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. August 2019 13:00
An: silverstripe/silverstripe-tagfield <silverstripe-tagfield@noreply.github.com>
Cc: Klaus Staudt <k-staudt@klaus-staudt.de>; Author <author@noreply.github.com>
Betreff: Re: [silverstripe/silverstripe-tagfield] SS4 Tagfield with AssetAdmin (#147)


Assuming this is a bug report, you can use the latest release branch 2.4.x-dev, it’s fixed there and will be released soon

**Comment by robbieaverill** [comment]
Hi, if you try the branch and it works for you we can tag it tomorrow

**Comment by klausjulius** [comment]
This would be very nice!! I will try it.
Please tell me if you released the branch and where

Von: Robbie Averill [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. August 2019 13:19
An: silverstripe/silverstripe-tagfield <silverstripe-tagfield@noreply.github.com>
Cc: Klaus Staudt <k-staudt@klaus-staudt.de>; Author <author@noreply.github.com>
Betreff: Re: [silverstripe/silverstripe-tagfield] SS4 Tagfield with AssetAdmin (#147)


Hi, if you try the branch and it works for you we can tag it tomorrow

**Comment by robbieaverill** [comment]
You can install 2.4.x-dev with composer

**Comment by klausjulius** [comment]
Hello Robbie Averill,

i have still the issue with tagfield and Assets.
Tags are saved in many_many but not shown.
I can see the saved Tags in Database but not in the
File Form.

In DataObjects tagfield is working very well but in Assets i cannot
See the saved tags.

I would be very grateful for any help

klaus

Von: Robbie Averill [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. August 2019 13:31
An: silverstripe/silverstripe-tagfield <silverstripe-tagfield@noreply.github.com>
Cc: Klaus Staudt <k-staudt@klaus-staudt.de>; Author <author@noreply.github.com>
Betreff: Re: [silverstripe/silverstripe-tagfield] SS4 Tagfield with AssetAdmin (#147)


You can install 2.4.x-dev with composer
