### ISSUE TITLE
StringTagField not initialized via Entwine

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-tagfield#148]
Since ["FIX Ensure tagfield is compatible with both React and Entwine contexts"](https://github.com/silverstripe/silverstripe-tagfield/commit/e97a82f0b7d7484a16e783b9432847659f8b0a9d) the StringTagField is no longer initialized via Entwine as it does not have the class "entwine" attached, which is required due to the [change in initialization](https://github.com/silverstripe/silverstripe-tagfield/commit/e97a82f0b7d7484a16e783b9432847659f8b0a9d#diff-5f55185ac07dc2877fd7f16a7cec6d4c). I assume that [adding the entwine class](https://github.com/silverstripe/silverstripe-tagfield/commit/e97a82f0b7d7484a16e783b9432847659f8b0a9d#diff-d072a5c333026c98dcf417dafdc8467dL204) in the Field method should be sufficient.

**Comment by asecondwill** [comment]
Same issue for me, SS4.3, TagField 2.4 does not show StringTagField, but does show TagFields 

Downgrading to 2.3 fixes.

**Comment by 107peo** [comment]
I also have this issue. Can't use TagField 2.4 as the fields just show up blank. Currently using 2.3

**Comment by elbroto** [comment]
Still broken in 2.5, please fix :)

**Comment by mlewis-everley** [comment]
Getting this as well with SS4.7.*.

Downgrading to 2.3.* fixes for me.

**Comment by lozcalver** [comment]
Still an issue, thankfully workaround is pretty simple - just use `->addExtraClass('entwine')`. PR: https://github.com/silverstripe/silverstripe-tagfield/pull/185

**Comment by 107p** [comment]
This is still not working. The StringTagField item shows up blank. 

The TagField.js is looking for the classes as follows. So both the .ss-tag-field and .entwine need to be there.
$('.js-injector-boot .ss-tag-field.entwine').entwine({

Can the TagField.js be updated to just look for $('.js-injector-boot .entwine'), otherwise it won't work.

This still hasn't worked properly since 2.3

**Comment by lozcalver** [comment]
You’re right @107p, I’d added the `ss-tag-field` class in my project code during testing and hadn’t removed it when I tested the PR 🤦. New PR to resolve this: https://github.com/silverstripe/silverstripe-tagfield/pull/187

**Comment by 107p** [comment]
Thanks @kinglozzer, now working as expected.

**Comment by emteknetnz** [comment]
Merged, backported (cherry-picked) and released [2.6.1](https://github.com/silverstripe/silverstripe-tagfield/releases/tag/2.6.1)
