### ISSUE TITLE
Readonly version of TagField does not respect title field

### ISSUE THREAD

**Issue by sb-relaxt-at** [silverstripe/silverstripe-tagfield#149]
When creating a readonly version the `titleField` property is not coppied. In TagField#performReadonlyTransformation there should be the following line added:

```
$copy->setTitleField($this->titleField);
```

**Comment by NightJar** [comment]
Thanks for reporting this issue @sb-relaxt-at 
Are you able to report also what versions this affects, or at least which version you have found this bug on?

It sounds like you have an appropriate solution for this, thanks for also taking the time to debug.
Would you like to open a pull request to contribute your solution to the project?

If you are unsure on the process for this, you can find an overview at https://docs.silverstripe.org/en/4/contributing/code/

**Comment by sb-relaxt-at** [comment]
Sorry for not responding. This has been fixed in the meantime by d11b9474ed868710a8739099224f6979263b8d4b

Thanks a lot :-)
