### ISSUE TITLE
Tags don't display in Assetadmin

### ISSUE THREAD

**Issue by klausjulius** [silverstripe/silverstripe-tagfield#150]
Hi together,

when creating a TagFiled 2.4 in an extension of assets, the tags are not visible after saving.
the tags are written in the database, but not displayed.

```php
class MosaikAssetFormFactoryExtension extends Extension {
   public function updateFormFields(FieldList $fields, $controller, $formName, $context)
    {
        if (isset($context['Record'])) {
           $MFile = $context['Record'];
           $fields->insertAfter('Title', TagField::create('Keywords', 'Schlagworte', MosaikKeywords::get(), 
              $MFile->Keywords(), 'Keyword')->setShouldLazyLoad(true)->setCanCreate(true)- 
                >setIsMultiple(true));
          // .....
          }
      }
}
```

in a DataObject class TagField works perfect.

thanks for your answer

Klausjulius

**Comment by ScopeyNZ** [comment]
We _just_ fixed this and tested it with asset admin. I don't have the code I was using to test it but I'm interested to see how our implementations differ.

@brynwhyman this would be worth looking into for a few minutes - might be just implementation detail or it could be some regression that can be classified further.

**Comment by brynwhyman** [comment]
Hi @klausjulius can you please confirm what version of `silverstripe/assets` and `silverstripe/asset-admin` you're running in your project?

**Comment by klausjulius** [comment]
> Hi @klausjulius can you please confirm what version of `silverstripe/assets` and `silverstripe/asset-admin` you're running in your project?

hi brynwhyman, where can i find the version. both where installed with silverstripe 4

**Comment by robbieaverill** [comment]
@klausjulius you can run `composer show` in your project root directory to get a list of the modules and versions installed

**Comment by klausjulius** [comment]
> @klausjulius you can run `composer show` in your project root directory to get a list of the modules and versions installed

thanks for the hint. i have installed assets 1.4.1 and asset-admin 1.4.1

**Comment by klausjulius** [comment]
> We _just_ fixed this and tested it with asset admin. I don't have the code I was using to test it but I'm interested to see how our implementations differ.
> 
> @brynwhyman this would be worth looking into for a few minutes - might be just implementation detail or it could be some regression that can be classified further.

**Comment by klausjulius** [comment]
> We _just_ fixed this and tested it with asset admin. I don't have the code I was using to test it but I'm interested to see how our implementations differ.
> 

Hi ScopeyNZ,

can you please tell me how you fixed it? which files of Tagfield are involved?

**Comment by ScopeyNZ** [comment]
Sorry Klaus I don't remember the issue or PR for it, I just remember the issue coming up and being resolved somehow

**Comment by klausjulius** [comment]
is there no possibility to make it run with asset-admin.

To reproduce:
`class MosaikKeywords extends DataObject
{
	private static $db = [
		'Title' => 'Varchar(200)',
        'Keyword' => 'Varchar'
    ];
	
	private static $belongs_many_many = [
        'File' => File::class,
		'Material' => MosaikMaterial::class,
    ];
	
	private static $table_name = 'MosaikKeywords';
}

class MosaikAssetFormFactoryExtension extends Extension
{
	public function updateFormFields(FieldList $fields, $controller, $formName, $context)
        {
			if (isset($context['Record'])) {
			$MFile = $context['Record'];
										
			$fields->insertAfter('Title', TagField::create('Keywords', 'Schlagworte', 
                                                        MosaikKeywords::get(), $MFile->Keywords(), 
                                                       'Keyword')>setShouldLazyLoad(true)
                                                        ->setCanCreate(true)->setIsMultiple(true));

class MosaikFileExtentions extends DataExtension  implements PermissionProvider
....
private static $many_many = [
        'Keywords' => MosaikKeywords::class,
....

in mysite.yml:
SilverStripe\Assets\File:
  extensions:
    - MosaikFileExtentions

SilverStripe\AssetAdmin\Forms\AssetFormFactory:
  extensions:
    - MosaikAssetFormFactoryExtension

`

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-tagfield/pull/162
