### ISSUE TITLE
TagField->getTags() should use "source" as it's base query

### ISSUE THREAD

**Issue by christopher-s** [silverstripe/silverstripe-tagfield#28]
Currently, if you use TagField it will pull all tags that exist for a particular data class.

However, it should be pulling tags that exist for instances of the data class (not global).

Here's the current code:

```
    protected function getTags($term) {
        /**
         * @var DataList $source
         */
        $source = $this->getSource();

        $dataClass = $source->dataClass();

        $titleField = $this->getTitleField();

        $term = Convert::raw2sql($term);

        $query = $dataClass::get()
            ->filter($titleField . ':PartialMatch:nocase', $term)
            ->sort($titleField)
            ->limit($this->getLazyLoadItemLimit());

        $items = array();

        foreach($query->map('ID', $titleField) as $id => $title) {
            if(!in_array($title, $items)) {
                $items[] = array(
                    'id' => $id,
                    'text' => $title
                );
            }
        }

        return $items;
    }
```

The fix is to change "$query = $dataClass::get()" to "$query = $source".

The $source is a DataList that contains a reference to the data class parent ID, so it will only pull tags as part of that instance.

This particular issue is prevalent if you use the "silverstripe-blog" module and have multiple blog instances.

I hope that makes sense. Thanks!

**Comment by talbet** [comment]
I've just run into this problem as well, creating a field that should only show tags from the parent page. Are there any other side effects from changing "$query = $dataClass::get()" to "$query = $source"? Should this change be merged?

**Comment by innomedia** [comment]
Had the same issue. Solved as mentioned above too.

**Comment by robbieaverill** [comment]
This is resolved in the SS4 version
