### ISSUE TITLE
Tags with spaces in them?

### ISSUE THREAD

**Issue by quamsta** [silverstripe/silverstripe-tagfield#51]
Right now the space key is used to denote the end of a tag name, but some desired tags might have more than one word.

Editing them in the CMS after the fact works, but it'd be nice if the autocomplete was a little smarter.

**Comment by danrye** [comment]
I agree this would be a nice feature, thanks for the workaround though, I didn't think to try and edit them after the fact.

**Comment by robbieaverill** [comment]
Tags with spaces in their names are supported in the SS4 version:

![image.png](https://images.zenhubusercontent.com/58409bdab9dc3c622022d20e/97f0b183-dee4-494c-b171-1d8dc0f8f2a2)
