### ISSUE TITLE
Duplicate Tags

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-tagfield#54]
Currently, the `TagField` allows a user to create a Tag DataObject with the same name multiple times. At least in some cases.

![screenshot from 2015-10-23 20 23 09](https://cloud.githubusercontent.com/assets/186158/10704122/24e55e2c-79c4-11e5-90e6-e4cfec1b15cf.png)

I believe what happened here is that the lazyloading suggest request was slow, so the user saw a Tag "Wasser" which he believed to be the existing tag, but instead it created a new one because the list to select existing ones was not loaded yet.

The solution should be pretty straight forward I think. In [`TagField->saveInto()`](https://github.com/silverstripe-labs/silverstripe-tagfield/blob/master/code/TagField.php#L284) we check if the submitted Tag is an ID or a String. If it's an ID it clearly is an existing tag, but if it's a string, it can be either a new tag or the above problem.
Would anything stop us from just doing a query at this point to look if a tag with that name already exists?
(Meaning: if I make a pull request that adds a check if that tag already exist, would this pull request be merged?)

**Comment by assertchris** [comment]
Yes

**Comment by Zauberfisch** [comment]
ok, so I have created a pull request #56 

I might have found another way to cause the issue of multiple bugs (which I think is fixed by that pull request).
You can seach for a tag with a space in front " Wasser", on submit, the space in front seems to be removed, so it submits "Wasser" twice, once as an ID to an existing Tag and once as the string.
This is possible also a user interface / javascript bug that we should look at in another issue/pull request.

**Comment by robbieaverill** [comment]
I think this was done with #58, feel free to reopen if not
