### ISSUE TITLE
"Create Tag" hint?

### ISSUE THREAD

**Issue by Zauberfisch** [silverstripe/silverstripe-tagfield#55]
Currently, there is no visual difference between selecting an existing Tag or creating a new one.
But often times this would be useful, to stop users from creating many tags with similar meaning because the user thinks that tag already exists. If he knew "Fooooo" alraedy existed, he might not create "Foo".

![screenshot from 2015-10-23 20 40 07](https://cloud.githubusercontent.com/assets/186158/10704517/db45ad78-79c6-11e5-89ea-41b992d30fa7.png)

I'd like to suggest adding a hint that something is being created:

![screenshot from 2015-10-23 20 40 43](https://cloud.githubusercontent.com/assets/186158/10704529/eb224e18-79c6-11e5-9c2a-b7a95ed0457a.png)

To make this feature flexible, I suggest the following behavoir:
- per default show "Create new '%s'" (from translation file)
- allow overwriting this with (eg `TagField->setCreateHint("Create '%s' as new tag")`)
- if a user does not want to have the hint
  - he can either change the translation to an empty string (global) 
  - or just for a single field with `TagField->setCreateHint('')`

**Comment by dhensby** [comment]
I like this idea

**Comment by robbieaverill** [comment]
This is resolved in the SS4 version:

![image.png](https://images.zenhubusercontent.com/58409bdab9dc3c622022d20e/05fee4a4-6b19-4112-a287-5edca1488333)
