### ISSUE TITLE
Tagfield CSS interferes with other select2 fields

### ISSUE THREAD

**Issue by micschk** [silverstripe/silverstripe-tagfield#76]
Tagfield's CSS includes some unnecessary !importants, and should generally be scoped to .field.tag

**Comment by tractorcow** [comment]
I agree; Maybe at the same time we could port all the css to SCSS and nest the rules properly.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

---

We don't use select2 any more in the SilverStripe 4 version of this module =)
