### ISSUE TITLE
Select2: No width when field is initially hidden

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-tagfield#78]
Hi,

I've recently added a TagField to the File DataObject. Following the instructions in this repo it works nicely on the standalone edit form, however when you use the inline edit form directly after uploading the TagField span generated by select2 has a `style="width: 2px"` attribute. I assume this is inherited from the select being invisible at the time.

If I modify TagField.js line 67-69 to this:

``` js
$select
    .chosenDestroy()
    .select2(options)
    // Kill the style attribute, let it be automatic
    .next()
    .removeProp('style');
```

... then it works by removing the whole style attribute and the field will then use an automatic width.

In terms of implementation, I've had to block the TagField.js file, copy it to mysite and require my modified copy again. This obviously isn't ideal.

I decided not to submit this change as a pull request because I haven't had time to investigate any side effects for other uses of the TagField addon, however it now works fine for both inline and standalone File edit forms.

**Caveat**: the width of the field is not 100% like the fields above it, but I don't mind that for my project.

**Comment by tractorcow** [comment]
What if you apply a fixed width via CSS to the select input? It probably needs a fixed width applied to the input at the time it's initially rendered. I suspect that will fix the render issue. :)

**Comment by robbieaverill** [comment]
A hard width and a style attribute with width didn't make a difference
unfortunately

On Tuesday, 22 March 2016, Damian Mooyman <notifications@github.com> wrote:

> What if you apply a fixed width via CSS to the select input? It probably
> needs a fixed width applied to the input at the time it's initially
> rendered. I suspect that will fix the render issue. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/silverstripe-labs/silverstripe-tagfield/issues/78#issuecomment-199640368>
>


-- 
*Robbie Averill*
LA PETITE MANOUCHE - NZ Gypsy Jazz Guitar Duo
Phone: +64 27 321 4758
contact@lapetitemanouche.com
www.lapetitemanouche.com

**Comment by Taitava** [comment]
Any update about this? :) I'm having this issue too.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

---

We don't use select2 in the SilverStripe 4 version of this module any more, so closing =)
