### ISSUE TITLE
Error: the method 'getcancreate' does not exist on 'StringTagField';

### ISSUE THREAD

**Issue by sanderha** [silverstripe/silverstripe-tagfield#82]
Im getting this error: ```the method 'getcancreate' does not exist on 'StringTagField'``` , on a SilverStripe 3.4 project. 
It seems to have something to do with line 167 in StringTagField:
``` $this->setAttribute('data-can-create', (int) $this->getCanCreate());``` 

the method indeed does not seem to exist on that class or any parent class.

Any ideas?

**Comment by dhensby** [comment]
this bug was introduced by https://github.com/silverstripe-labs/silverstripe-tagfield/pull/81

It looks like stringtagfield doens't extend tagfied so it doesn't share the same API

We need to add that function to the StringTagField it seems.

Is this something you'd be able to do @sanderha ?

**Comment by sanderha** [comment]
Sure. I guess its more or less copying the functionality from TagField

**Comment by dhensby** [comment]
I guess so :)

**Comment by sanderha** [comment]
#83  created a PR

**Comment by tractorcow** [comment]
Fixed with #83
