### ISSUE TITLE
Compatibility issue with SS3.5.1?

### ISSUE THREAD

**Issue by toddkimball** [silverstripe/silverstripe-tagfield#88]
I've installed the TagField module alongside the latest version of the Blog module and am getting the following from in my error log: 

Class 'TagField' not found in /home/charles/www/blog/code/model/BlogPost.php on line 259

I've attempted to recreate using a custom DataObject and ran into the same error. Could this be a compatability issue with SS v3.5.2?

**Comment by dhensby** [comment]
Sounds like you didn't "flush" https://docs.silverstripe.org/en/3/developer_guides/performance/caching/#cleaning-caches-on-flush-1-requests

**Comment by toddkimball** [comment]
Nope, flushed (even went to the extent of flushing both front & backend, flush=1 AND flush=all).  Same error. Could this be because of the changes made for 4.0 compat?  I'll try with an earlier version if I can find one later and see how that pans out as well.

**Comment by dhensby** [comment]
if you've run `composer require silverstripe/tagfield` it'll automatically pull in a version compatible with your existing code, it shouldn't pull in a 4.x compatible version.

**Comment by toddkimball** [comment]
Re-ran composer after a quick code exorcism, all is well. Let's pretend this never happened...
