### ISSUE TITLE
Remove empty Tab ?

### ISSUE THREAD

**Issue by neilcreagh** [silverstripe/silverstripe-tagfield#94]
I've added the tagfield to a data object, in the main tab:
`$fields->addFieldToTab("Root.Main", TagField::create(
	'LocationTags',
	'Location Tags',
	LocationTag::get(),
	$this->LocationTags()
)
	->setShouldLazyLoad(true) // tags should be lazy loaded
	->setCanCreate(true));`
but now there's an empty Tab called 'Location Tags'. 
If I use `$fields->removeByName("LocationTags");` then my tagfield in the Main area disappears too.

**Comment by dhensby** [comment]
Use `$fields->removeByName("Root.LocationTags");`
