### ISSUE TITLE
TagField close button styling not the same as ListBox close button

### ISSUE THREAD

**Issue by fspringveldt** [silverstripe/silverstripe-tagfield#98]
There is an issue with how the 'x' button is displayed in SS4. This screenshot is taken from the Blog Modules' Post Options tab, where the fields Categories and Tags uses TagField, whereas the Authors uses the default framework scaffolding to render it (which I think is Listbox)

![image](https://user-images.githubusercontent.com/10938392/30617891-3b2f7c8c-9dec-11e7-9f22-d7fe196cd81a.png)

**Comment by zanderwar** [comment]
![image](https://user-images.githubusercontent.com/13566916/32358917-92e77260-c0ae-11e7-9fab-bd143f670205.png)

There is currently no close button at all as per #102

**Comment by robbieaverill** [comment]
It's an entirely different component now. I'm going to close this - there are some issues to track the core form field updates e.g. https://github.com/silverstripe/silverstripe-admin/issues/52
